"""
This module is meant to test that the functions/methods/classes from /src/cmaputils/census/fips.py work.
"""

"""
Author: Aaron Rumph
Date: 05/26/2026
Description: Module containing tests for FIPS codes (since generated by Macros)
Input Files: N/A
Output Files: N/A
"""

# SECTION: External dependencies

# SECTION: Internal dependencies
import cmaputils.census.fips as fips

# SECTION: Constants


# SECTION: Tests
def test_fips_import():
    # will fail if import throws exception
    import cmaputils.census.fips._county


def test_fips_cmap_counties():
    assert fips.COOK_COUNTY_IL == "031"
    assert fips.DUPAGE_COUNTY_IL == "043"
    assert fips.KANE_COUNTY_IL == "089"
    assert fips.KENDALL_COUNTY_IL == "093"
    assert fips.LAKE_COUNTY_IL == "097"
    assert fips.MCHENRY_COUNTY_IL == "111"
    assert fips.WILL_COUNTY_IL == "197"


def test_fips_california_county_num():
    california_county_num = len(fips.CALIFORNIA_COUNTY_CODES)
    assert california_county_num == 58


def test_fips_illinois_county_num():
    illinois_county_num = len(fips.ILLINOIS_COUNTY_CODES)
    assert illinois_county_num == 102


def test_all_counties_illinois_importable():
    illinois_states_list = fips.ILLINOIS_COUNTY_CODES.keys()
    # TODO: test that all fips codes for illinois are importable
